INSERT INTO RECETE_DETAYI VALUES (6001, 1);  -- Dilay -> Coraspin (ID: 1)
INSERT INTO RECETE_DETAYI VALUES (6002, 16); -- Hilal -> Nexium (ID: 16)
INSERT INTO RECETE_DETAYI VALUES (6003, 4);  -- Davut -> Ebixa (ID: 4)
INSERT INTO RECETE_DETAYI VALUES (6004, 13); -- Fevzi -> Parol (ID: 13)
INSERT INTO RECETE_DETAYI VALUES (6005, 14); -- Yavuz -> Arveles (ID: 14)
INSERT INTO RECETE_DETAYI VALUES (6006, 11); -- Toprak -> Bepanthol (ID: 11)
INSERT INTO RECETE_DETAYI VALUES (6007, 8);  -- Zeynep Şimal -> Selectra (ID: 8)
INSERT INTO RECETE_DETAYI VALUES (6008, 7);  -- Ömer Faruk -> Cipralex (ID: 7)
INSERT INTO RECETE_DETAYI VALUES (6009, 10); -- Efe -> Priorin (ID: 10)
INSERT INTO RECETE_DETAYI VALUES (6010, 2);  -- Ahmet -> Beloc Zok (ID: 2)
INSERT INTO RECETE_DETAYI VALUES (6011, 5);  -- Mehmet -> Donecept (ID: 5)
INSERT INTO RECETE_DETAYI VALUES (6012, 8);  -- Selectra
INSERT INTO RECETE_DETAYI VALUES (6013, 16); -- Nexium
INSERT INTO RECETE_DETAYI VALUES (6014, 11); -- Bepanthol
INSERT INTO RECETE_DETAYI VALUES (6015, 18); -- Calpol
INSERT INTO RECETE_DETAYI VALUES (6016, 19); -- Augmentin ES
INSERT INTO RECETE_DETAYI VALUES (6017, 13); -- Parol
INSERT INTO RECETE_DETAYI VALUES (6018, 2);  -- Beloc Zok
INSERT INTO RECETE_DETAYI VALUES (6019, 4);  -- Ebixa
INSERT INTO RECETE_DETAYI VALUES (6020, 7);  -- Cipralex
INSERT INTO RECETE_DETAYI VALUES (6021, 16); -- Nexium
INSERT INTO RECETE_DETAYI VALUES (6022, 11); -- Bepanthol
INSERT INTO RECETE_DETAYI VALUES (6023, 24); -- Buscopan
INSERT INTO RECETE_DETAYI VALUES (6024, 11); -- Bepanthol
INSERT INTO RECETE_DETAYI VALUES (6025, 14); -- Arveles
INSERT INTO RECETE_DETAYI VALUES (6026, 2);  -- Beloc Zok
INSERT INTO RECETE_DETAYI VALUES (6027, 4);  -- Ebixa
INSERT INTO RECETE_DETAYI VALUES (6028, 9);  -- Xanax
INSERT INTO RECETE_DETAYI VALUES (6029, 24); -- Buscopan
INSERT INTO RECETE_DETAYI VALUES (6030, 12); -- Roaccutane
INSERT INTO RECETE_DETAYI VALUES (6031, 11); -- Bepanthol
INSERT INTO RECETE_DETAYI VALUES (6032, 21); -- Majezik
INSERT INTO RECETE_DETAYI VALUES (6033, 20); -- Apranax Fort
INSERT INTO RECETE_DETAYI VALUES (6034, 1);  -- Coraspin
INSERT INTO RECETE_DETAYI VALUES (6035, 5);  -- Donecept
INSERT INTO RECETE_DETAYI VALUES (6036, 8);  -- Selectra
INSERT INTO RECETE_DETAYI VALUES (6037, 16); -- Nexium
INSERT INTO RECETE_DETAYI VALUES (6038, 10); -- Priorin
INSERT INTO RECETE_DETAYI VALUES (6039, 17); -- Dolven
INSERT INTO RECETE_DETAYI VALUES (6040, 13); -- Parol
INSERT INTO RECETE_DETAYI VALUES (6041, 14); -- Arveles
INSERT INTO RECETE_DETAYI VALUES (6042, 2);  -- Beloc Zok
INSERT INTO RECETE_DETAYI VALUES (6043, 4);  -- Ebixa
INSERT INTO RECETE_DETAYI VALUES (6044, 7);  -- Cipralex
INSERT INTO RECETE_DETAYI VALUES (6045, 16); -- Nexium
INSERT INTO RECETE_DETAYI VALUES (6046, 11); -- Bepanthol
INSERT INTO RECETE_DETAYI VALUES (6047, 24); -- Buscopan
INSERT INTO RECETE_DETAYI VALUES (6048, 20); -- Apranax Fort

-- *** MÜKERRER ZİYARET DETAYLARI ***
INSERT INTO RECETE_DETAYI VALUES (6049, 3);  -- Dilay'ın 2. ilacı: Ecopirin (ID: 3)
INSERT INTO RECETE_DETAYI VALUES (6050, 20); -- Hilal'in 2. ilacı: Apranax Fort (ID: 20)
INSERT INTO RECETE_DETAYI VALUES (6051, 5);  -- Davut'un 2. ilacı: Donecept (ID: 5)
INSERT INTO RECETE_DETAYI VALUES (6052, 1);  -- Dilay'ın 3. ilacı: Coraspin (ID: 1 - Tekrar alım)

COMMIT;